import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import StylesProvider from "@/theme/StylesProvider";
import { HandContextProvider } from "@/contexts/HandContext";
import HeaderComponent from "@/components/header/Header";
import Head from "next/head";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </Head>
      <body>
        <StyledComponentsRegistry>
          <StylesProvider>
            <HandContextProvider>
              <HeaderComponent />
              {children}
            </HandContextProvider>
          </StylesProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
